add missing fixtures to test/functional/wiki_controller_test.rb
Tests fail randomly.

<pre>
  1) Error:
WikiControllerTest#test_show_with_sidebar:
ActionView::Template::Error: undefined method `name' for nil:NilClass
    app/helpers/application_helper.rb:797:in `block in parse_redmine_links'
    app/helpers/application_helper.rb:757:in `gsub!'
    app/helpers/application_helper.rb:757:in `parse_redmine_links'
    app/helpers/application_helper.rb:601:in `block (2 levels) in textilizable'
    app/helpers/application_helper.rb:600:in `each'
    app/helpers/application_helper.rb:600:in `block in textilizable'
    app/helpers/application_helper.rb:621:in `parse_non_pre_blocks'
    app/helpers/application_helper.rb:599:in `textilizable'
    app/views/wiki/_content.html.erb:2:in `_app_views_wiki__content_html_erb___3773333740575742579_33736820'
    app/views/wiki/show.html.erb:44:in `_app_views_wiki_show_html_erb__965327089377623997_33504680'
    app/controllers/wiki_controller.rb:97:in `show'
    test/functional/wiki_controller_test.rb:119:in `test_show_with_sidebar'
</pre>

It can be reproduced by following change.

<pre>
 class WikiControllerTest < ActionController::TestCase
   fixtures :projects, :users, :roles, :members, :member_roles,
            :enabled_modules, :wikis, :wiki_pages, :wiki_contents,
-           :wiki_content_versions, :attachments
+           :wiki_content_versions, :attachments,
+           :issues redmine-, :issue_statuses
</pre>

git-svn-id: https://svn.redmine.org/redmine/trunk@13590 e93f8b46-1217-0410-a6f0-8f06a7374b81