Fix NoMethodError: undefined method `rake_run' for Rails::TestUnit::Runner:Class (NoMethodError) after updating to Rails 7.1 (redmine-36320, redmine-39803)
Patch by @tohosaku.

git-svn-id: https://svn.redmine.org/redmine/trunk@22517 e93f8b46-1217-0410-a6f0-8f06a7374b81