add missing fixtures to CalendarsControllerTest
Tests fail randomly.

<pre>
  1) Error:
CalendarsControllerTest#test_cross_project_calendar:
ActionView::Template::Error: undefined method `name' for nil:NilClass
    app/helpers/issues_helper.rb:57:in `render_issue_tooltip'
    app/views/common/_calendar.html.erb:17:in `block in _app_views_common__calendar_html_erb__4084073314711523042_57686480'
    app/views/common/_calendar.html.erb:12:in `each'
    app/views/common/_calendar.html.erb:12:in `_app_views_common__calendar_html_erb__4084073314711523042_57686480'
    app/views/calendars/show.html.erb:30:in `_app_views_calendars_show_html_erb___1639405444546230501_53808060'
    test/functional/calendars_controller_test.rb:44:in `test_cross_project_calendar'
</pre>

git-svn-id: https://svn.redmine.org/redmine/trunk@13503 e93f8b46-1217-0410-a6f0-8f06a7374b81